TOPLEVEL_DOMAIN = $(shell cat /etc/puavo/topdomain)

OPENSSL_CONF  = -config ../puavo-ca.cnf
OPENSSL_INFRA = workdir workdir/index.txt workdir/newcerts workdir/serial

NEW_SERIAL_COMMAND = dd if=/dev/urandom bs=1 count=64 2>/dev/null | md5sum | cut -b 1-16 > workdir/serial

SUBJECTALTNAME =
export SUBJECTALTNAME
