source 'http://rubygems.org'

group :development, :test do
  gem 'byebug'
end

group :development do
  # Access an interactive console on exception pages or by calling 'console'
  # anywhere in the code.
  gem 'web-console'
  gem 'listen'
end
#
gem 'net-ldap'
gem 'pg'
gem 'puma'
gem 'rails'
gem 'sqlite3'
gem 'unicorn'
